train:
  num_episodes: 1000
  max_steps_per_episode: 10000
  epsilon_start: 1.0
  epsilon_decay: 0.995
  epsilon_min: 0.05
  gamma: 0.99
  lr: 0.001
  batch_size: 64
  buffer_size: 100000
  target_update_freq: 10
  save_interval: 50

test:
  num_episodes: 5

env:
  max_x: 5000
  max_y: 5000
  low_speed_limit: 0.5
  slow_window_size: 100
  reward_target_speed: 15

misc:
  seed: 42
  device: cuda
  verbose: true